<?php 

return [
    'sidebar' => [
        ['header' => 'Main Menu'],
        [
            'title' => 'Dashboard',
            'icon'  => 'feather icon-home',
            'url'   => '/dashboard',
            'route_name' => 'dashboard',
        ],

        ['header' => 'Content Manager'],
        [
            'title' => 'Category',
            'icon'  => 'feather icon-list',
            'url'   => '/categories',
            'route_name' => 'categories.index',
        ],
        [
            'title' => 'Posts',
            'icon'  => 'feather icon-file-text',
            'url'   => '/posts',
            'route_name' => 'posts.index',
        ],

        ['header' => 'Media & Gallery'],
        [
            'title' => 'Page',
            'icon'  => 'feather icon-folder',
            'url'   => '/pages',
            'route_name' => 'pages.index',
        ],
        [
            'title' => 'Album',
            'icon'  => 'feather icon-folder',
            'url'   => '/albums',
            'route_name' => 'albums.index',
        ],
        [
            'title' => 'Gallery',
            'icon'  => 'feather icon-image',
            'url'   => '/galleries',
            'route_name' => 'galleries.index',
        ],
        [
            'title' => 'Video',
            'icon'  => 'feather icon-video',
            'url'   => '/videos',
            'route_name' => 'videos.index',
        ],
        [
            'title' => 'Slider',
            'icon'  => 'feather icon-monitor',
            'url'   => '/sliders',
            'route_name' => 'sliders.index',
        ],
        [
            'title' => 'Lembaga',
            'icon'  => 'feather icon-monitor',
            'url'   => '/lembagas',
            'route_name' => 'lembagas.index',
        ],

        ['header' => 'Information'],
        [
            'title' => 'Agenda',
            'icon'  => 'feather icon-calendar',
            'url'   => '/agendas',
            'route_name' => 'agendas.index',
        ],
        [
            'title' => 'Announcement',
            'icon'  => 'feather icon-bell',
            'url'   => '/announcements',
            'route_name' => 'announcements.index',
        ],
        [
            'title' => 'Inbox',
            'icon'  => 'feather icon-mail',
            'url'   => '/inboxes',
            'route_name' => 'inboxes.index',
            'badge' => ['class' => 'badge-primary', 'text' => 'new'],
        ],
        ['header' => 'Team Manager'],
        [
            'title' => 'Position',
            'icon'  => 'feather icon-map-pin',
            'url'   => '/positions',
            'route_name' => 'positions.index',
        ],
        [
            'title' => 'Team',
            'icon'  => 'feather icon-users',
            'url'   => '/teams',
            'route_name' => 'teams.index',
        ],

        ['header' => 'System'],
        [
            'title' => 'Users',
            'icon'  => 'feather icon-users',
            'url'   => '/users',
            'route_name' => 'users.index',
        ],
        [
            'title' => 'Roles',
            'icon'  => 'feather icon-shield',
            'url'   => '/roles',
            'route_name' => 'roles.index',
        ],
        [
            'title' => 'Permissions',
            'icon'  => 'feather icon-lock',
            'url'   => '/permissions',
            'route_name' => 'permissions.index',
        ],
        [
            'title' => 'Social Media',
            'icon'  => 'feather icon-share-2',
            'url'   => '/social_media',
            'route_name' => 'social_media.index',
        ],
        [
            'title' => 'Setting',
            'icon'  => 'feather icon-settings',
            'url'   => '/settings',
            'route_name' => 'settings.index',
        ],
        [
            'title' => 'Navigation',
            'icon'  => 'feather icon-menu',
            'url'   => '/navigations',
            'route_name' => 'navigations.index',
        ],
    ],
    'marketing' => [
        'navbar' => [
            [
                'title' => 'Home',
                'title_id' => 'Beranda',
                'title_en' => 'Home',
                'title_ar' => 'الرئيسية',
                'url' => '/',
            ],
            [
                'title' => 'About',
                'title_id' => 'Tentang',
                'title_en' => 'About',
                'title_ar' => 'من نحن',
                'url' => '/about',
                'route_name' => 'about-marketing',
            ],
            [
                'title' => 'Events',
                'title_id' => 'Agenda',
                'title_en' => 'Events',
                'title_ar' => 'الفعاليات',
                'url' => '/events',
                'route_name' => 'events-marketing',
            ],
            [
                'title' => 'Team',
                'title_id' => 'Tim',
                'title_en' => 'Team',
                'title_ar' => 'الفريق',
                'url' => '/team',
                'route_name' => 'teams-marketing',
            ],
            [
                'title' => 'Announcements',
                'title_id' => 'Pengumuman',
                'title_en' => 'Announcements',
                'title_ar' => 'الإعلانات',
                'url' => '/announcement',
                'route_name' => 'announcements-marketing',
            ],
            [
                'title' => 'Gallery',
                'title_id' => 'Galeri',
                'title_en' => 'Gallery',
                'title_ar' => 'المعرض',
                'url' => '/gallery',
                'route_name' => 'gallery-marketing',
            ],
            [
                'title' => 'Articles',
                'title_id' => 'Artikel',
                'title_en' => 'Articles',
                'title_ar' => 'المقالات',
                'url' => '/articles',
                'route_name' => 'articles-marketing',
            ],
        ],
        'footer' => [
            [
                'title' => 'About',
                'title_id' => 'Tentang',
                'title_en' => 'About',
                'title_ar' => 'من نحن',
                'url' => '/about',
                'route_name' => 'about-marketing',
            ],
            [
                'title' => 'Events',
                'title_id' => 'Agenda',
                'title_en' => 'Events',
                'title_ar' => 'الفعاليات',
                'url' => '/events',
                'route_name' => 'events-marketing',
            ],
            [
                'title' => 'Team',
                'title_id' => 'Tim',
                'title_en' => 'Team',
                'title_ar' => 'الفريق',
                'url' => '/team',
                'route_name' => 'teams-marketing',
            ],
            [
                'title' => 'Announcements',
                'title_id' => 'Pengumuman',
                'title_en' => 'Announcements',
                'title_ar' => 'الإعلانات',
                'url' => '/announcement',
                'route_name' => 'announcements-marketing',
            ],
            [
                'title' => 'Gallery',
                'title_id' => 'Galeri',
                'title_en' => 'Gallery',
                'title_ar' => 'المعرض',
                'url' => '/gallery',
                'route_name' => 'gallery-marketing',
            ],
            [
                'title' => 'Articles',
                'title_id' => 'Artikel',
                'title_en' => 'Articles',
                'title_ar' => 'المقالات',
                'url' => '/articles',
                'route_name' => 'articles-marketing',
            ],
            [
                'title' => 'Contact',
                'title_id' => 'Kontak',
                'title_en' => 'Contact',
                'title_ar' => 'اتصل بنا',
                'url' => '/contact',
                'route_name' => 'contact-marketing',
            ],
        ],
    ],
];
